### DISCUSSION TITLE
Newbie to your actions script

### DISCUSSION THREAD

**Discussion by codenamedpkt** [JamesIves/github-sponsors-readme-action#349] [Q&A]
Hi @JamesIves,
This is Mr. Alice from Mr. Poon's Studio which is preparing to announce my establishment.

In your `README.md` mentioned of `<!-- sponsors --><!-- sponsors -->`, took the online research with mine. It should `<!-- sponsors:START --><!-- sponsors:END -->` in your documentation. Moreover, when I using your action script provided from your GitHub Marketplace, when I directly copy and paste theres having troubles here in following scrnshot.

Here's the actions script codes you are providing:
```yaml
- name: Add GitHub Sponsors to Readme
  uses: JamesIves/github-sponsors-readme-action@v1.0.8
```

The correct one should put into your GitHub Marketplace yaml code is following:

```yaml
name: Add GitHub Sponsors to Readme
on:
  - pull_request
  - push
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3.0.2

      - name: List current folder location, files and show users GitHub token
        run: |
          pwd
          ls -a
          ls -a .github
          ls -a .github/workflows
          echo "Your GitHub secrets is ${{ secrets.GITHUB_TOKEN }}."

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: 'sponsor.me.md'

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: '.'
```

Please update that.

Finally, you have not tell GitHub coders where to place their profile/sponsor profile whom GitHub Sponsors enabled. Please mention in the `README.md` where to place their profile under `<!-- sponsors --><!-- sponsors -->`. Or it will recieveing the follow warning: `Unable to locate markers in your file. Please check the documentation and try again. ⚠️`

@codenamedpkt
