### DISCUSSION TITLE
ENOENT: no such file or directory, open 'README.md', did I do something wrong?

### DISCUSSION THREAD

**Discussion by Jieiku** [JamesIves/github-sponsors-readme-action#362] [Q&A] [answered]
I apologize if I have made a simple mistake, I don't have an enormous amount of github experience. (This is actually the first github action I have EVER tried implementing)

I added your sponsors readme action by creating the file in my repository: `.github/workflows/actions.yml`:

```yml
name: Generate Sponsors README
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Sponsors
        uses: JamesIves/github-sponsors-readme-action@v1.0.8
        with:
          token: ${{ secrets.PAT }}
```

I then went to my repository settings, and added a repository actions secret with a name of 'PAT' and with the value of the Token that I generated with read:user access.

Here is my repository: https://github.com/Jieiku/abridge

Here is the [build log](https://github.com/Jieiku/abridge/runs/6631745460?check_suite_focus=true):
```
Run JamesIves/github-sponsors-readme-action@v1.0.8
  with:
    token: ***

    GitHub Sponsors Readme Action 💖

    🚀 Getting Started Guide: https://github.com/JamesIves/github-sponsors-readme-action
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-sponsors-readme-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-sponsors-readme-action/issues

    📣 Maintained by James Ives: https://jamesiv.es
    💖 Support: https://github.com/sponsors/JamesIves
Checking configuration and initializing… 🚚
Fetching data from the GitHub API as User… ⚽
Generating updated README.md file… 📁
Error: There was an error generating the updated file: ENOENT: no such file or directory, open 'README.md' ❌
There was an error generating sponsors. ❌
```

Really appreciate any help, thank you, I will of coarse keep searching for the answer and come back and update this if I figure it out before your response.
