### DISCUSSION TITLE
Provide users GitHub Profile `homepage` value

### DISCUSSION THREAD

**Discussion by robingenz** [JamesIves/github-sponsors-readme-action#445] [Ideas]
It would be great if we could not only link the sponsor's GitHub profile in the template, but also the homepage they provided in their github profile (in my case: `https://robingenz.dev/`).

Example:
```yml
- name: Update `Sponsors` section
  uses: JamesIves/github-sponsors-readme-action@releases/v1-org
  with:
    token: ${{ secrets.PAT }}
    file: 'README.md'
    organization: true
    template: '<a href="{{{ homepage }}}"><img src="https://github.com/{{{ login }}}.png" alt="{{{ login }}}" width="50px"></a>'
```
