### DISCUSSION TITLE
Does The Action Scrape custom tiers as well to collect sponsors with minimum and maximum logic

### DISCUSSION THREAD

**Discussion by tallguyjenks** [JamesIves/github-sponsors-readme-action#673] [Q&A] [answered]
I implemented the Github action 

```yaml
name: Generate Sponsors README
on:
  workflow_dispatch:
  schedule:
    - cron: "* 3 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PERSONAL_AUTH_TOKEN }}
          file: "README.md"
          minimum: 2900

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PERSONAL_AUTH_TOKEN }}
          branch: main
          folder: "."
```

and it works perfectly.

However i used the `minimum: 2900`
value with the action per the documentation and my custom sponsor at $30 or `3000` was not picked up by the job.

Feature request is that the job also scrapes the custom tiers if not by default then at least when the `minimum` or `maximum` criteria are set

thanks for the great GitHub action!
