### DISCUSSION TITLE
master' is already used, There is nothing to commit

### DISCUSSION THREAD

**Discussion by qishibo** [JamesIves/github-sponsors-readme-action#852] [Q&A] [answered]
I want to update my README.md directly in master but failed
my yaml file like bellow
```yaml
name: Generate Sponsors README
on:
  push
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PAT }}
          file: 'README.md'
          template: '<a href="https://github.com/{{ login }}"><img src="{{ avatarUrl }}" width="60px" alt="{{ name }}" style="border-radius: 50%;" /></a>'

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: '.'
```

but I got a fetal error `fatal: 'master' is already used` and finally `There is nothing to commit. Exiting early…`, so I am quite confused about this, is there any issues in my yaml file?
 Tips: runs in https://github.com/qishibo/github-action-test/actions/runs/11495236537/job/31994328587

```
fatal: 'master' is already used by worktree at '/home/runner/work/github-action-test/github-action-test'
Error encountered while checking out branch. Attempting to continue with a new branch name.
/usr/bin/git checkout -B temp-1729757429936 origin/master
Switched to a new branch 'temp-1729757429936'
branch 'temp-1729757429936' set up to track 'origin/master'.
/usr/bin/git config --global --add safe.directory /home/runner/work/github-action-test/github-action-test/github-pages-deploy-action-temp-deployment-folder
/usr/bin/chmod -R +rw /home/runner/work/github-action-test/github-action-test
/usr/bin/rsync -q -av --checksum --progress /home/runner/work/github-action-test/github-action-test/. github-pages-deploy-action-temp-deployment-folder --delete --exclude CNAME --exclude .nojekyll --exclude .ssh --exclude .git --exclude .github --exclude github-pages-deploy-action-temp-deployment-folder
Checking if there are files to commit…
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/o0risvqez
Switched to a new branch 'github-pages-deploy-action/o0risvqez'
/usr/bin/chmod -R +rw github-pages-deploy-action-temp-deployment-folder
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
There is nothing to commit. Exiting early… 📭
```

**Comment by JamesIves** [comment]
Can you log what `README.md` file looks like between the generate sponsors job and the deploy job? If there's no content between the markers it's likely the scope of your personal access token causing the failure. If there is, we'll likely need to debug the deployment step instead.

**Comment by qishibo** [comment]
@JamesIves I don't think casued by PAT, I've gave almost all permissions.
here is my README.md
![image](https://github.com/user-attachments/assets/84fa74dd-36b4-4a7f-9c97-e50fb4b66892)

and I can't see what's the result of the final README, but it show successfully
![image](https://github.com/user-attachments/assets/0a1ec6f1-bf51-496c-9683-fec5e9ee9a59)
 but I got a fetal error like this, is this the reason?
![image](https://github.com/user-attachments/assets/59f34ef4-8e95-4074-b912-02272cd53e53)

**Reply by JamesIves** [reply]
Can you run `cat README.md` right before the deployment job runs and see if the actual README file is updated by searching for the sponsor flags? This isn't always exactly an error as the action should recover from this, so I want to verify if that early exit is valid or not.

Something like this:

```yaml
      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PAT }}
          file: 'README.md'
          template: '<a href="https://github.com/{{ login }}"><img src="{{ avatarUrl }}" width="60px" alt="{{ name }}" style="border-radius: 50%;" /></a>'
    
     - name: Read README
     - run: |
        cat README.md

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: '.'

```

Something I'd like to add in a future update is a log here that shows how much sponsor data the action retrieves to make this sort of debugging easier 🤔
