### ISSUE TITLE
Error: `Cannot read property 'viewer' of undefined ❌`

### ISSUE THREAD

**Issue by robingenz** [JamesIves/github-sponsors-readme-action#429]
## Describe the bug

The following error occurs when running the action: 

```
Error: There was an error generating the updated file: Cannot read property 'viewer' of undefined ❌
```

See https://github.com/capawesome-team/capacitor-firebase/runs/7670530335?check_suite_focus=true

## Reproduction Steps

Start the workflow with the provided configuration in an organization.

## Logs

```
Run JamesIves/github-sponsors-readme-action@v1
  with:
    token: ***
    file: README.md
    organization: true
    minimum: 5

    GitHub Sponsors Readme Action 💖

    🚀 Getting Started Guide: https://github.com/JamesIves/github-sponsors-readme-action
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-sponsors-readme-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-sponsors-readme-action/issues

    📣 Maintained by James Ives: https://jamesiv.es/
    💖 Support: https://github.com/sponsors/JamesIves
Checking configuration and initializing… 🚚
Fetching data from the GitHub API as Organization… ⚽
Generating updated README.md file… 📁
Generating template… ✨
Error: There was an error generating the updated file: Cannot read property 'viewer' of undefined ❌
There was an error generating sponsors. ❌
```

See https://github.com/capawesome-team/capacitor-firebase/runs/7670530335?check_suite_focus=true

## Workflow

```yml
name: Generate Sponsors README

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Sponsors README
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PAT }}
          file: 'README.md'
          organization: true
          minimum: 5
```

Source: https://github.com/capawesome-team/capacitor-firebase/blob/main/.github/workflows/sponsors.yml

## Additional Comments

Thank you for this awesome project!

**Comment by JamesIves** [comment]
At a glance it looks like your PAT doesn't have the correct permission scope to read sponsors for your organization. Which permissions did you give it?

**Comment by robingenz** [comment]
![grafik](https://user-images.githubusercontent.com/13857929/182847731-eecd9edf-29a7-463f-8f8b-9094cdb17375.png)


`read:org` as  mentioned here: https://github.com/JamesIves/github-sponsors-readme-action#optional-choices

**Comment by robingenz** [comment]
Do you have any other ideas? I would really like to use your action because it does exactly what I need. 😄  Do you need any more info?

**Comment by JamesIves** [comment]
Sorry I've been away for the last couple weeks.

Does the account you generated the PAT from have read permissions of the org you're requesting the information from? 

Besides that you can try running the following query within https://docs.github.com/en/graphql/overview/explorer and see if it works properly. As I don't have an organization I can properly test this with it's entirely possible that the query needs some adjusting for organization level requests. The query can be found on line 21 here: https://github.com/JamesIves/github-sponsors-readme-action/blob/dev/src/template.ts

**Comment by robingenz** [comment]
Thank you for your response!

That is the result of the query in line 21 (with `action.organization = true`):

```graphql
{
  "data": {
    "viewer": {
      "login": "robingenz",
      "sponsorshipsAsMaintainer": {
        "totalCount": 0,
        "pageInfo": {
          "endCursor": null
        },
        "nodes": []
      }
    }
  }
}
```

------

However, I got it working with another query in the GraphQL API Explorer:

```graphql
query { 
  organization (login: "capawesome-team") {
    sponsorshipsAsMaintainer (first: 100) {
      totalCount
      nodes {
        sponsorEntity {
          ... on User {
            login
          }
        }
      }
    }
  }
}
```

There I got the following result (which is correct):

```
{
  "data": {
    "organization": {
      "sponsorshipsAsMaintainer": {
        "totalCount": 1,
        "nodes": [
          {
            "sponsorEntity": {
              "login": "bastifix"
            }
          }
        ]
      }
    }
  }
}
```

So seems to be a problem with the query. Can i provide more information to you?

**Comment by JamesIves** [comment]
Thanks for looking into that. I've made a potential fix but could do with your help verifying it if you're able to. Can you point your workflow to the following version: `uses: JamesIves/github-sponsors-readme-action@releases/v1-org` and let me know if this correctly collects the org level sponsors? 

If not I'll run some checks on an org I have access to tomorrow morning to get this working.

**Comment by robingenz** [comment]
> Thanks for looking into that. I've made a potential fix but could do with your help verifying it if you're able to. Can you point your workflow to the following version: `uses: JamesIves/github-sponsors-readme-action@releases/v1-org` and let me know if this correctly collects the org level sponsors?
> 
> If not I'll run some checks on an org I have access to tomorrow morning to get this working.

Thank you for your work!

Unfortunately it did not work.
This is the result: https://github.com/capawesome-team/capacitor-firebase/runs/7858429335?check_suite_focus=true

**Comment by JamesIves** [comment]
Should hopefully work now if you try again, appears that `GITHUB_ACTOR` was not the right variable to get the org login - you may need to give your PAT `read:user` permissions also

**Comment by robingenz** [comment]
> Should hopefully work now if you try again, appears that `GITHUB_ACTOR` was not the right variable to get the org login - you may need to give your PAT `read:user` permissions also

I tried that (permission `read:user` was necessary). The job completed successfully, but my README was not updated.
Action log: https://github.com/capawesome-team/capacitor-firebase/runs/7861134078?check_suite_focus=true
I have 1 sponsor currently (see the result in this [comment](https://github.com/JamesIves/github-sponsors-readme-action/issues/429#issuecomment-1215100826)).

**Comment by JamesIves** [comment]
Looks like you're missing a step to commit the README changes back to your project; try adding this to your workflow file;

```yaml
- name: Deploy to GitHub Pages 🚀
   uses: JamesIves/github-pages-deploy-action@v4
   with:
     branch: main
     folder: '.'
```

Combined;

```yaml
name: Generate Sponsors README

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Sponsors README
        uses: JamesIves/github-sponsors-readme-action@releases/v1-org
        with:
          token: ${{ secrets.PAT }}
          file: 'README.md'
          organization: true
          minimum: 5
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: '.'
```

This will update the README template in the workflow context, and then make a commit back to your org repo. You may also need to provide the deploy step with `token: ${{ secrets.PAT }}` also. (You can try without first though as it uses a built in token that should provide adequate permissions) 

For an example of how I leverage this action in my other projects you can view a working [sponsors.yaml](https://github.com/JamesIves/github-pages-deploy-action/blob/dev/.github/workflows/sponsors.yml) file here. I have it update on a timed cron which updates my sponsors daily, I also split the template up so higher tiered subscribers get a larger avatar.  😄
