### ISSUE TITLE
There was an error generating sponsors. ❌ - Cannot read 'viewer' of undefined

### ISSUE THREAD

**Issue by adi1090x** [JamesIves/github-sponsors-readme-action#450]
## Failed to generate sponsors

the previous version was working fine, now i get this error after new release : **`Error: There was an error generating the updated file: Cannot read property 'viewer' of undefined ❌`**

```
> Run JamesIves/github-sponsors-readme-action@v1

    GitHub Sponsors Readme Action 💖

    🚀 Getting Started Guide: https://github.com/JamesIves/github-sponsors-readme-action
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-sponsors-readme-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-sponsors-readme-action/issues

    📣 Maintained by James Ives: https://jamesiv.es/
    💖 Support: https://github.com/sponsors/JamesIves
Checking configuration and initializing… 🚚
Fetching data from the GitHub API as User… ⚽
Generating updated README.md file… 📁
Generating template… ✨
Error: There was an error generating the updated file: Cannot read property 'viewer' of undefined ❌
There was an error generating sponsors. ❌
```

## Here's my workflow yml

File : `.github/workflows/sponsors.yml`

```yml
name: Generate Sponsors README
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PAT_GHS }}
          file: 'README.md'

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: '.'
```
PAT has a scope `user:read` as well. 
Is this a bug in new release, or I'm doing something wrong here?
