### ISSUE TITLE
Run this workflow with cron to automate the process

### ISSUE THREAD

**Issue by adi1090x** [JamesIves/github-sponsors-readme-action#469]
Hello @JamesIves 

This is not an issue, I just want an example to run this workflow with cron to automate the process.
With the current example on your Github readme, the job only runs on push on a selected branch.
```yml
name: Generate Sponsors README
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.GH_PAT_SPSR }}
          file: 'README.md'

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: '.'
```

I'm trying to run this workflow with cron, but have no luck as i'm no expert in github actions. I've tried this, But it did not work: (every minute for just testing)
```yml
name: Generate Sponsors README

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.GH_PAT_SPSR }}
          file: 'README.md'

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: '.'
``` 

Can you please provide as example `yml` to run your github action with cron.

**Comment by JamesIves** [comment]
README has been updated!

**Comment by adi1090x** [comment]
Thank you.

BTW, This `yml` worked as well, Not sure why it did not work yesterday, But when i checked the repo today, It worked.

```yml
name: Generate Sponsors README

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.GH_PAT_SPSR }}
          file: 'README.md'

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: '.'
```
![Screenshot_2022-09-06-15-29-47_1920x1080](https://user-images.githubusercontent.com/26059688/188607821-deaa56ba-b94c-46de-be98-869c3cafbeae.png)

Closing the issue.
