### ISSUE TITLE
Cannot read properties of undefined (reading 'viewer')

### ISSUE THREAD

**Issue by dawsbot** [JamesIves/github-sponsors-readme-action#723]
## Describe the bug

When running a fresh installation for my personal profile I received the following error: "`Cannot read properties of undefined (reading 'viewer')`"

## Reproduction Steps

Run it here: https://github.com/dawsbot/dawsbot/actions/runs/7748704237/job/21131844682#step:3:46

## Logs

```
Run JamesIves/github-sponsors-readme-action@v1


     ██████╗ ██╗████████╗██╗  ██╗██╗   ██╗██████╗                       
    ██╔════╝ ██║╚══██╔══╝██║  ██║██║   ██║██╔══██╗                      
    ██║  ███╗██║   ██║   ███████║██║   ██║██████╔╝                      
    ██║   ██║██║   ██║   ██╔══██║██║   ██║██╔══██╗                      
    ╚██████╔╝██║   ██║   ██║  ██║╚██████╔╝██████╔╝                      
     ╚═════╝ ╚═╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ╚═════╝                       
                                                                        
    ███████╗██████╗  ██████╗ ███╗   ██╗███████╗ ██████╗ ██████╗ ███████╗
    ██╔════╝██╔══██╗██╔═══██╗████╗  ██║██╔════╝██╔═══██╗██╔══██╗██╔════╝
    ███████╗██████╔╝██║   ██║██╔██╗ ██║███████╗██║   ██║██████╔╝███████╗
    ╚════██║██╔═══╝ ██║   ██║██║╚██╗██║╚════██║██║   ██║██╔══██╗╚════██║
    ███████║██║     ╚██████╔╝██║ ╚████║███████║╚██████╔╝██║  ██║███████║
    ╚══════╝╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
                                                                        
    ██████╗ ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗                 
    ██╔══██╗██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝                 
    ██████╔╝█████╗  ███████║██║  ██║██╔████╔██║█████╗                   
    ██╔══██╗██╔══╝  ██╔══██║██║  ██║██║╚██╔╝██║██╔══╝                   
    ██║  ██║███████╗██║  ██║██████╔╝██║ ╚═╝ ██║███████╗                 
    ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚═╝     ╚═╝╚══════╝                 
                                                                        
     █████╗  ██████╗████████╗██╗ ██████╗ ███╗   ██╗                     
    ██╔══██╗██╔════╝╚══██╔══╝██║██╔═══██╗████╗  ██║                     
    ███████║██║        ██║   ██║██║   ██║██╔██╗ ██║                     
    ██╔══██║██║        ██║   ██║██║   ██║██║╚██╗██║                     
    ██║  ██║╚██████╗   ██║   ██║╚██████╔╝██║ ╚████║                     
    ╚═╝  ╚═╝ ╚═════╝   ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝                     
                                                                        
    🚀 Getting Started Guide: https://github.com/JamesIves/github-sponsors-readme-action
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-sponsors-readme-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-sponsors-readme-action/issues

    📣 Maintained by James Ives: https://jamesiv.es/
    💖 Support: https://github.com/sponsors/JamesIves
Checking configuration and initializing… 🚚
Fetching data from the GitHub API as User… ⚽
Generating updated README.md file… 📁
Generating template… ✨
Error: There was an error generating the updated file: Cannot read properties of undefined (reading 'viewer') ❌
There was an error generating sponsors. ❌
```

## Workflow

```yml
name: Generate Sponsors README
on:
  workflow_dispatch:
  schedule:
    - cron: 30 15 * * 0-6
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PAT }}
          file: "README.md"

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: "."
```
