### ISSUE TITLE
Not working for me after follow the steps

### ISSUE THREAD

**Issue by diegoulloao** [JamesIves/github-sponsors-readme-action#769]
I've followed all the steps, i've created the PAT with read:user and read:org permissions, I've added it to secrets (actions) in the repository where the value is the PAT generated, and finally, I've put the `<!-- sponsors --><!--sponsors-->` marker in my readme file, but it doesn't work.

This is my yaml:
```yaml
name: Generate Sponsors README
on:
  workflow_dispatch:
  schedule:
    - cron: 30 15 * * 0-6
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate Sponsors ❤️
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PAT }}
          file: "README.md"
```

This is the result when I check the action logs:

```
📣 Maintained by James Ives: https://jamesiv.es/
    💖 Support: https://github.com/sponsors/JamesIves
Checking configuration and initializing… 🚚
Fetching data from the GitHub API as User… ⚽
Generating updated README.md file… 📁
Generating template… ✨
The data was successfully retrieved and saved! ✅ 💖
```

It seems all good. But I get an empty sponsors section.

README: https://github.com/diegoulloao/neofusion.k9s/blob/main/README.md#sponsors-%EF%B8%8F

## Reproduction Steps

I'm just following the doc steps.

## Logs

Logs above.

## Workflow

Workflow above.

## Additional Comments

I'm missing something?

**Comment by JamesIves** [comment]
This action only makes the modifications to the README file locally, it does not deploy the changes or commit it to a specific branch. In order for this to work you need to pair it with a deployment step, there's an example of this [in the README](https://github.com/JamesIves/github-sponsors-readme-action?tab=readme-ov-file#getting-started-%EF%B8%8F) using another action I maintain, but if you prefer you can use any of the available ones on the marketplace. The separation is intentional here as to make the action responsible for a single task in an effort to not add lots of complicated git logic.

You'll need to modify your workflow file with something like the following:

```yml
name: Generate Sponsors README
on:
  workflow_dispatch:
  schedule:
    - cron: 30 15 * * 0-6
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate Sponsors ❤️
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PAT }}
          file: "README.md"

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: '.'
```

There's also a full working example that this project uses to generate its README information [here](https://github.com/JamesIves/github-sponsors-readme-action/blob/dev/.github/workflows/sponsors.yml).

**Comment by diegoulloao** [comment]
Actually I checked those examples, but I'm not using GitHub pages. Mine's is just a public repository.

**Comment by JamesIves** [comment]
All that action does is move things to different branches and runs the necessary git commands. You can run the git commands yourself in that step too to commit the README changes back to the base branch also, but adding that step will automate the whole process for you with minimal config.

**Comment by diegoulloao** [comment]
> All that action does is move things to different branches and runs the necessary git commands. You can run the git commands yourself in that step too to commit the README changes back to the base branch also, but adding that step will automate the whole process for you with minimal config.

If I understand right, adding that step will do the job of committing changes to my main branch regardless of wether I'm using github pages or not?

**Comment by diegoulloao** [comment]
Actually it doesn't, I've tried adding the step before, I did it again and I get this error:
```bash
Checking if there are files to commit…
/usr/bin/git add --all .
/usr/bin/git checkout -b github-pages-deploy-action/tbamsejhj
Switched to a new branch 'github-pages-deploy-action/tbamsejhj'
/usr/bin/git commit -m Deploying to main from @ diegoulloao/neofusion.k9s@2e5c9[66](https://github.com/diegoulloao/neofusion.k9s/actions/runs/9356712787/job/25754803373#step:4:67)0daaaeaab6f8b7d6222cc315670174d02 🚀 --quiet --no-verify
Force-pushing changes...
/usr/bin/git push --force ***github.com/diegoulloao/neofusion.k9s.git github-pages-deploy-action/tbamsejhj:main
remote: Permission to diegoulloao/neofusion.k9s.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/diegoulloao/neofusion.k9s.git/': The requested URL returned error: 403
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/tbamsejhj
Reset branch 'github-pages-deploy-action/tbamsejhj'
/usr/bin/chmod -R +rw github-pages-deploy-action-temp-deployment-folder
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Notice: Deployment failed! ❌
```

My PAT has `read:user` and `read:org` permissions.

**Comment by JamesIves** [comment]
That's correct. You'll need to share your updated workflow, unless you are deploying to an org repository or a repo owned by another user it shouldn't matter what your PAT has as it should default to the built in GitHub token.

**Comment by diegoulloao** [comment]
> That's correct. You'll need to share your updated workflow, unless you are deploying to an org repository or a repo owned by another user it shouldn't matter what your PAT has as it should default to the built in GitHub token.

I'm testing again, new project, not working again, idk why... (user account)

```
Force-pushing changes...
/usr/bin/git push --force ***github.com/diegoulloao/sponsors-readme-workflow.git github-pages-deploy-action/z96or7nf8:main
remote: Permission to diegoulloao/sponsors-readme-workflow.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/diegoulloao/sponsors-readme-workflow.git/': The requested URL returned error: 403
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/z96or7nf8
Reset branch 'github-pages-deploy-action/z96or7nf8'
/usr/bin/chmod -R +rw github-pages-deploy-action-temp-deployment-folder
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Notice: Deployment failed! ❌
```

**token**

<img width="294" alt="Screenshot 3" src="https://github.com/JamesIves/github-sponsors-readme-action/assets/45423661/2907ed05-7727-46de-864f-a6caed8e7c88">

<br />

<img width="176" alt="Screenshot 4" src="https://github.com/JamesIves/github-sponsors-readme-action/assets/45423661/995aeaa0-3390-4f5b-9f8f-463e73882059">

Repo: https://github.com/diegoulloao/sponsors-readme-workflow (public)
Workflow: https://github.com/diegoulloao/sponsors-readme-workflow/blob/main/.github/workflows/sponsors.yml

Not working.

**Comment by JamesIves** [comment]
Try adding the following to your workflow

```yml
permissions:
  contents: write
```

Here's the full example:

```yml
name: Generate Sponsors README
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PAT }}
          file: "README.md"

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: "."
```

I've mirrored this suggestion in the README as it was only present in the deploy step repo.
